// GENERATED by scripts/gen-size-constants.ts from the "new master" Excel
// files — do not hand-edit the data blocks; re-run the script instead.
// Helpers at the bottom are hand-written.

export const FITTING_SIZES = {
  BW_CS_AS: [
  "0.5\"NB X SCH STD",
  "0.5\"NB X SCH 40",
  "0.5\"NB X SCH XS",
  "0.5\"NB X SCH 80",
  "0.5\"NB X SCH 160",
  "0.5\"NB X SCH XXS",
  "0.75\"NB X SCH STD",
  "0.75\"NB X SCH 40",
  "0.75\"NB X SCH XS",
  "0.75\"NB X SCH 80",
  "0.75\"NB X SCH 160",
  "0.75\"NB X SCH XXS",
  "1\"NB X SCH STD",
  "1\"NB X SCH 40",
  "1\"NB X SCH XS",
  "1\"NB X SCH 80",
  "1\"NB X SCH 160",
  "1\"NB X SCH XXS",
  "1.25\"NB X SCH STD",
  "1.25\"NB X SCH 40",
  "1.25\"NB X SCH XS",
  "1.25\"NB X SCH 80",
  "1.25\"NB X SCH 160",
  "1.25\"NB X SCH XXS",
  "1.5\"NB X SCH STD",
  "1.5\"NB X SCH 40",
  "1.5\"NB X SCH XS",
  "1.5\"NB X SCH 80",
  "1.5\"NB X SCH 160",
  "1.5\"NB X SCH XXS",
  "2\"NB X SCH STD",
  "2\"NB X SCH 40",
  "2\"NB X SCH XS",
  "2\"NB X SCH 80",
  "2\"NB X SCH 160",
  "2\"NB X SCH XXS",
  "2.5\"NB X SCH STD",
  "2.5\"NB X SCH 40",
  "2.5\"NB X SCH XS",
  "2.5\"NB X SCH 80",
  "2.5\"NB X SCH 160",
  "2.5\"NB X SCH XXS",
  "3\"NB X SCH STD",
  "3\"NB X SCH 40",
  "3\"NB X SCH XS",
  "3\"NB X SCH 80",
  "3\"NB X SCH 160",
  "3\"NB X SCH XXS",
  "4\"NB X SCH STD",
  "4\"NB X SCH 40",
  "4\"NB X SCH XS",
  "4\"NB X SCH 80",
  "4\"NB X SCH 120",
  "4\"NB X SCH 160",
  "4\"NB X SCH XXS",
  "5\"NB X SCH STD",
  "5\"NB X SCH 40",
  "5\"NB X SCH XS",
  "5\"NB X SCH 80",
  "5\"NB X SCH 120",
  "5\"NB X SCH 160",
  "5\"NB X SCH XXS",
  "6\"NB X SCH STD",
  "6\"NB X SCH 40",
  "6\"NB X SCH XS",
  "6\"NB X SCH 80",
  "6\"NB X SCH 120",
  "6\"NB X SCH 160",
  "6\"NB X SCH XXS",
  "8\"NB X SCH 20",
  "8\"NB X SCH 30",
  "8\"NB X SCH STD",
  "8\"NB X SCH 40",
  "8\"NB X SCH 60",
  "8\"NB X SCH XS",
  "8\"NB X SCH 80",
  "8\"NB X SCH 100",
  "8\"NB X SCH 120",
  "8\"NB X SCH 140",
  "8\"NB X SCH 160",
  "8\"NB X SCH XXS",
  "10\"NB X SCH 20",
  "10\"NB X SCH 30",
  "10\"NB X SCH STD",
  "10\"NB X SCH 40",
  "10\"NB X SCH 60",
  "10\"NB X SCH XS",
  "10\"NB X SCH 80",
  "10\"NB X SCH 100",
  "10\"NB X SCH 120",
  "10\"NB X SCH 140",
  "10\"NB X SCH 160",
  "10\"NB X SCH XXS",
  "12\"NB X SCH 20",
  "12\"NB X SCH 30",
  "12\"NB X SCH STD",
  "12\"NB X SCH 40",
  "12\"NB X SCH 60",
  "12\"NB X SCH XS",
  "12\"NB X SCH 80",
  "12\"NB X SCH 100",
  "12\"NB X SCH 120",
  "12\"NB X SCH 140",
  "12\"NB X SCH 160",
  "12\"NB X SCH XXS",
  "14\"NB X SCH 20",
  "14\"NB X SCH 30",
  "14\"NB X SCH STD",
  "14\"NB X SCH 40",
  "14\"NB X SCH 60",
  "14\"NB X SCH XS",
  "14\"NB X SCH 80",
  "14\"NB X SCH 100",
  "14\"NB X SCH 120",
  "14\"NB X SCH 140",
  "14\"NB X SCH 160",
  "16\"NB X SCH 20",
  "16\"NB X SCH 30",
  "16\"NB X SCH STD",
  "16\"NB X SCH 40",
  "16\"NB X SCH 60",
  "16\"NB X SCH XS",
  "16\"NB X SCH 80",
  "16\"NB X SCH 100",
  "16\"NB X SCH 120",
  "16\"NB X SCH 140",
  "16\"NB X SCH 160",
  "18\"NB X SCH 20",
  "18\"NB X SCH 30",
  "18\"NB X SCH STD",
  "18\"NB X SCH 40",
  "18\"NB X SCH 60",
  "18\"NB X SCH XS",
  "18\"NB X SCH 80",
  "18\"NB X SCH 100",
  "18\"NB X SCH 120",
  "18\"NB X SCH 140",
  "18\"NB X SCH 160",
  "20\"NB X SCH 20",
  "20\"NB X SCH 30",
  "20\"NB X SCH STD",
  "20\"NB X SCH 40",
  "20\"NB X SCH 60",
  "20\"NB X SCH XS",
  "20\"NB X SCH 80",
  "20\"NB X SCH 100",
  "20\"NB X SCH 120",
  "20\"NB X SCH 140",
  "20\"NB X SCH 160",
  "22\"NB X SCH 20",
  "22\"NB X SCH 30",
  "22\"NB X SCH STD",
  "22\"NB X SCH 40",
  "22\"NB X SCH 60",
  "22\"NB X SCH XS",
  "22\"NB X SCH 80",
  "22\"NB X SCH 100",
  "22\"NB X SCH 120",
  "22\"NB X SCH 140",
  "22\"NB X SCH 160",
  "24\"NB X SCH 20",
  "24\"NB X SCH 30",
  "24\"NB X SCH STD",
  "24\"NB X SCH 40",
  "24\"NB X SCH 60",
  "24\"NB X SCH XS",
  "24\"NB X SCH 80",
  "24\"NB X SCH 100",
  "24\"NB X SCH 120",
  "24\"NB X SCH 140",
  "24\"NB X SCH 160",
  "24\"NB X SCH 10"
],
  BW_SS_DS: [
  "0.5\"NB X SCH 5S",
  "0.5\"NB X SCH 10S",
  "0.5\"NB X SCH 40S",
  "0.5\"NB X SCH 80S",
  "0.5\"NB X SCH 160",
  "0.5\"NB X SCH XXS",
  "0.75\"NB X SCH 5S",
  "0.75\"NB X SCH 10S",
  "0.75\"NB X SCH 40S",
  "0.75\"NB X SCH 80S",
  "0.75\"NB X SCH 160",
  "0.75\"NB X SCH XXS",
  "1\"NB X SCH 5S",
  "1\"NB X SCH 10S",
  "1\"NB X SCH 40S",
  "1\"NB X SCH 80S",
  "1\"NB X SCH 160",
  "1\"NB X SCH XXS",
  "1.25\"NB X SCH 5S",
  "1.25\"NB X SCH 10S",
  "1.25\"NB X SCH 40S",
  "1.25\"NB X SCH 80S",
  "1.25\"NB X SCH 160",
  "1.25\"NB X SCH XXS",
  "1.5\"NB X SCH 5S",
  "1.5\"NB X SCH 10S",
  "1.5\"NB X SCH 40S",
  "1.5\"NB X SCH 80S",
  "1.5\"NB X SCH 160",
  "1.5\"NB X SCH XXS",
  "2\"NB X SCH 5S",
  "2\"NB X SCH 10S",
  "2\"NB X SCH 40S",
  "2\"NB X SCH 80S",
  "2\"NB X SCH 160",
  "2\"NB X SCH XXS",
  "2.5\"NB X SCH 5S",
  "2.5\"NB X SCH 10S",
  "2.5\"NB X SCH 40S",
  "2.5\"NB X SCH 80S",
  "2.5\"NB X SCH 160",
  "2.5\"NB X SCH XXS",
  "3\"NB X SCH 5S",
  "3\"NB X SCH 10S",
  "3\"NB X SCH 40S",
  "3\"NB X SCH 80S",
  "3\"NB X SCH 160",
  "3\"NB X SCH XXS",
  "4\"NB X SCH 5S",
  "4\"NB X SCH 10S",
  "4\"NB X SCH 40S",
  "4\"NB X SCH 80S",
  "4\"NB X SCH 120",
  "4\"NB X SCH 160",
  "4\"NB X SCH XXS",
  "5\"NB X SCH 5S",
  "5\"NB X SCH 10S",
  "5\"NB X SCH 40S",
  "5\"NB X SCH 80S",
  "5\"NB X SCH 120",
  "5\"NB X SCH 160",
  "5\"NB X SCH XXS",
  "6\"NB X SCH 5S",
  "6\"NB X SCH 10S",
  "6\"NB X SCH 40S",
  "6\"NB X SCH 80S",
  "6\"NB X SCH 120",
  "6\"NB X SCH 160",
  "6\"NB X SCH XXS",
  "8\"NB X SCH 5S",
  "8\"NB X SCH 10S",
  "8\"NB X SCH 40S",
  "8\"NB X SCH 80S",
  "8\"NB X SCH 60",
  "8\"NB X SCH 100",
  "8\"NB X SCH 120",
  "8\"NB X SCH 140",
  "8\"NB X SCH 160",
  "8\"NB X SCH XXS",
  "10\"NB X SCH 5S",
  "10\"NB X SCH 10S",
  "10\"NB X SCH 40S",
  "10\"NB X SCH 80S",
  "10\"NB X SCH 60",
  "10\"NB X SCH 100",
  "10\"NB X SCH 120",
  "10\"NB X SCH 140",
  "10\"NB X SCH 160",
  "10\"NB X SCH XXS",
  "12\"NB X SCH 5S",
  "12\"NB X SCH 10S",
  "12\"NB X SCH 40S",
  "12\"NB X SCH 80S",
  "12\"NB X SCH 60",
  "12\"NB X SCH 100",
  "12\"NB X SCH 120",
  "12\"NB X SCH 140",
  "12\"NB X SCH 160",
  "12\"NB X SCH XXS",
  "14\"NB X SCH 5S",
  "14\"NB X SCH 10S",
  "14\"NB X SCH 40S",
  "14\"NB X SCH 80S",
  "14\"NB X SCH 60",
  "14\"NB X SCH 100",
  "14\"NB X SCH 120",
  "14\"NB X SCH 140",
  "14\"NB X SCH 160",
  "16\"NB X SCH 5S",
  "16\"NB X SCH 10S",
  "16\"NB X SCH 40S",
  "16\"NB X SCH 80S",
  "16\"NB X SCH 60",
  "16\"NB X SCH 100",
  "16\"NB X SCH 120",
  "16\"NB X SCH 140",
  "16\"NB X SCH 160",
  "18\"NB X SCH 5S",
  "18\"NB X SCH 10S",
  "18\"NB X SCH 40S",
  "18\"NB X SCH 80S",
  "18\"NB X SCH 60",
  "18\"NB X SCH 100",
  "18\"NB X SCH 120",
  "18\"NB X SCH 140",
  "18\"NB X SCH 160",
  "20\"NB X SCH 5S",
  "20\"NB X SCH 10S",
  "20\"NB X SCH 40S",
  "20\"NB X SCH 80S",
  "20\"NB X SCH 60",
  "20\"NB X SCH 100",
  "20\"NB X SCH 120",
  "20\"NB X SCH 140",
  "20\"NB X SCH 160",
  "22\"NB X SCH 5S",
  "22\"NB X SCH 10S",
  "22\"NB X SCH 40S",
  "22\"NB X SCH 80S",
  "22\"NB X SCH 60",
  "22\"NB X SCH 100",
  "22\"NB X SCH 120",
  "22\"NB X SCH 140",
  "22\"NB X SCH 160",
  "24\"NB X SCH 5S",
  "24\"NB X SCH 10S",
  "24\"NB X SCH 40S",
  "24\"NB X SCH 80S",
  "24\"NB X SCH 60",
  "24\"NB X SCH 100",
  "24\"NB X SCH 120",
  "24\"NB X SCH 140",
  "24\"NB X SCH 160"
],
  SW: [
  "1/8\"NB X 3000#",
  "1/4\"NB X 3000#",
  "3/8\"NB X 3000#",
  "0.5\"NB X 3000#",
  "0.75\"NB X 3000#",
  "1\"NB X 3000#",
  "1.25\"NB X 3000#",
  "1.5\"NB X 3000#",
  "2\"NB X 3000#",
  "2-0.5\"NB X 3000#",
  "3\"NB X 3000#",
  "4\"NB X 3000#",
  "1/8\"NB X 6000#",
  "1/4\"NB X 6000#",
  "3/8\"NB X 6000#",
  "0.5\"NB X 6000#",
  "0.75\"NB X 6000#",
  "1\"NB X 6000#",
  "1.25\"NB X 6000#",
  "1.5\"NB X 6000#",
  "2\"NB X 6000#",
  "2-0.5\"NB X 6000#",
  "3\"NB X 6000#",
  "4\"NB X 6000#",
  "0.5\"NB X 9000#",
  "0.75\"NB X 9000#",
  "1\"NB X 9000#",
  "1.25\"NB X 9000#",
  "1.5\"NB X 9000#",
  "2\"NB X 9000#"
],
  THRD: [
  "1/8\"NB X 2000#",
  "1/4\"NB X 2000#",
  "3/8\"NB X 2000#",
  "0.5\"NB X 2000#",
  "0.75\"NB X 2000#",
  "1\"NB X 2000#",
  "1.25\"NB X 2000#",
  "1.5\"NB X 2000#",
  "2\"NB X 2000#",
  "2-0.5\"NB X 2000#",
  "3\"NB X 2000#",
  "4\"NB X 2000#",
  "1/8\"NB X 3000#",
  "1/4\"NB X 3000#",
  "3/8\"NB X 3000#",
  "0.5\"NB X 3000#",
  "0.75\"NB X 3000#",
  "1\"NB X 3000#",
  "1.25\"NB X 3000#",
  "1.5\"NB X 3000#",
  "2\"NB X 3000#",
  "2-0.5\"NB X 3000#",
  "3\"NB X 3000#",
  "4\"NB X 3000#",
  "1/8\"NB X 6000#",
  "1/4\"NB X 6000#",
  "3/8\"NB X 6000#",
  "0.5\"NB X 6000#",
  "0.75\"NB X 6000#",
  "1\"NB X 6000#",
  "1.25\"NB X 6000#",
  "1.5\"NB X 6000#",
  "2\"NB X 6000#",
  "2-0.5\"NB X 6000#",
  "3\"NB X 6000#",
  "4\"NB X 6000#"
],
};

export const FLANGE_SIZES: { label: string; dim: string }[] = [
  {
    "label": "0.5\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "0.75\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1.25\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1.5\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "2\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "2.5\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "3\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "4\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "5\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "6\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "8\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "10\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "12\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "14\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "16\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "18\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "20\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "22\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "24\"NB X 150#",
    "dim": "ASME B16.5"
  },
  {
    "label": "0.5\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "0.75\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1.25\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1.5\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "2\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "2.5\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "3\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "4\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "5\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "6\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "8\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "10\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "12\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "14\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "16\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "18\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "20\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "22\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "24\"NB X 300#",
    "dim": "ASME B16.5"
  },
  {
    "label": "0.5\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "0.75\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1.25\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1.5\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "2\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "2.5\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "3\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "4\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "5\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "6\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "8\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "10\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "12\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "14\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "16\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "18\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "20\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "22\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "24\"NB X 400#",
    "dim": "ASME B16.5"
  },
  {
    "label": "0.5\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "0.75\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1.25\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1.5\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "2\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "2.5\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "3\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "4\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "5\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "6\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "8\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "10\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "12\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "14\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "16\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "18\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "20\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "22\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "24\"NB X 600#",
    "dim": "ASME B16.5"
  },
  {
    "label": "0.5\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "0.75\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1.25\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1.5\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "2\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "2.5\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "3\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "4\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "5\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "6\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "8\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "10\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "12\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "14\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "16\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "18\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "20\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "22\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "24\"NB X 900#",
    "dim": "ASME B16.5"
  },
  {
    "label": "0.5\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "0.75\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1.25\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1.5\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "2\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "2.5\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "3\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "4\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "5\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "6\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "8\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "10\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "12\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "14\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "16\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "18\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "20\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "22\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "24\"NB X 1500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "0.5\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "0.75\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1.25\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "1.5\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "2\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "2.5\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "3\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "4\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "5\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "6\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "8\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "10\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "12\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "14\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "16\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "18\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "20\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "22\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "24\"NB X 2500#",
    "dim": "ASME B16.5"
  },
  {
    "label": "26\"NB X 150#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "28\"NB X 150#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "30\"NB X 150#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "32\"NB X 150#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "34\"NB X 150#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "36\"NB X 150#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "38\"NB X 150#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "40\"NB X 150#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "42\"NB X 150#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "44\"NB X 150#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "46\"NB X 150#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "48\"NB X 150#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "50\"NB X 150#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "52\"NB X 150#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "54\"NB X 150#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "56\"NB X 150#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "58\"NB X 150#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "60\"NB X 150#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "26\"NB X 300#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "28\"NB X 300#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "30\"NB X 300#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "32\"NB X 300#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "34\"NB X 300#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "36\"NB X 300#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "38\"NB X 300#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "40\"NB X 300#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "42\"NB X 300#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "44\"NB X 300#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "46\"NB X 300#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "48\"NB X 300#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "50\"NB X 300#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "52\"NB X 300#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "54\"NB X 300#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "56\"NB X 300#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "58\"NB X 300#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "60\"NB X 300#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "26\"NB X 400#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "28\"NB X 400#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "30\"NB X 400#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "32\"NB X 400#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "34\"NB X 400#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "36\"NB X 400#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "38\"NB X 400#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "40\"NB X 400#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "42\"NB X 400#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "44\"NB X 400#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "46\"NB X 400#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "48\"NB X 400#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "50\"NB X 400#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "52\"NB X 400#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "54\"NB X 400#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "56\"NB X 400#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "58\"NB X 400#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "60\"NB X 400#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "26\"NB X 600#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "28\"NB X 600#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "30\"NB X 600#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "32\"NB X 600#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "34\"NB X 600#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "36\"NB X 600#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "38\"NB X 600#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "40\"NB X 600#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "42\"NB X 600#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "44\"NB X 600#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "46\"NB X 600#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "48\"NB X 600#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "50\"NB X 600#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "52\"NB X 600#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "54\"NB X 600#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "56\"NB X 600#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "58\"NB X 600#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "60\"NB X 600#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "26\"NB X 900#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "28\"NB X 900#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "30\"NB X 900#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "32\"NB X 900#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "34\"NB X 900#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "36\"NB X 900#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "38\"NB X 900#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "40\"NB X 900#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "42\"NB X 900#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "44\"NB X 900#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "46\"NB X 900#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "48\"NB X 900#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "50\"NB X 900#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "52\"NB X 900#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "54\"NB X 900#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "56\"NB X 900#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "58\"NB X 900#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "60\"NB X 900#",
    "dim": "ASME B16.47 Sr. A"
  },
  {
    "label": "26\"NB X 75#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "28\"NB X 75#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "30\"NB X 75#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "32\"NB X 75#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "34\"NB X 75#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "36\"NB X 75#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "38\"NB X 75#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "40\"NB X 75#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "42\"NB X 75#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "44\"NB X 75#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "46\"NB X 75#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "48\"NB X 75#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "50\"NB X 75#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "52\"NB X 75#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "54\"NB X 75#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "56\"NB X 75#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "58\"NB X 75#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "60\"NB X 75#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "26\"NB X 150#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "28\"NB X 150#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "30\"NB X 150#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "32\"NB X 150#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "34\"NB X 150#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "36\"NB X 150#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "38\"NB X 150#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "40\"NB X 150#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "42\"NB X 150#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "44\"NB X 150#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "46\"NB X 150#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "48\"NB X 150#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "50\"NB X 150#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "52\"NB X 150#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "54\"NB X 150#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "56\"NB X 150#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "58\"NB X 150#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "60\"NB X 150#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "26\"NB X 300#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "28\"NB X 300#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "30\"NB X 300#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "32\"NB X 300#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "34\"NB X 300#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "36\"NB X 300#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "38\"NB X 300#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "40\"NB X 300#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "42\"NB X 300#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "44\"NB X 300#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "46\"NB X 300#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "48\"NB X 300#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "50\"NB X 300#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "52\"NB X 300#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "54\"NB X 300#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "56\"NB X 300#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "58\"NB X 300#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "60\"NB X 300#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "26\"NB X 400#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "28\"NB X 400#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "30\"NB X 400#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "32\"NB X 400#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "34\"NB X 400#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "36\"NB X 400#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "26\"NB X 600#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "28\"NB X 600#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "30\"NB X 600#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "32\"NB X 600#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "34\"NB X 600#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "36\"NB X 600#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "26\"NB X 900#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "28\"NB X 900#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "30\"NB X 900#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "32\"NB X 900#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "34\"NB X 900#",
    "dim": "ASME B16.47 Sr. B"
  },
  {
    "label": "36\"NB X 900#",
    "dim": "ASME B16.47 Sr. B"
  }
];

// ── helpers (hand-written) ──────────────────────────────────────────────────

// End connection from the product-name suffix convention:
// ", SW" → socket weld, ", SCRD" → threaded (NPT), otherwise butt-weld (SMLS).
export function getFittingEnds(product: string): "BW" | "SW" | "NPT" {
  if (/,\s*SW$/i.test(product)) return "SW";
  if (/,\s*SCRD$/i.test(product)) return "NPT";
  return "BW";
}

// Prefer the item's actual ends value (autofilled from the master row) over
// the name-suffix convention, so custom master products that don't follow
// the ", SW"/", SCRD" naming still route to the right pool.
export function getFittingSizeOptions(product: string, knownEnds?: string): string[] {
  const ends = knownEnds === "SW" || knownEnds === "NPT" || knownEnds === "BW"
    ? knownEnds
    : getFittingEnds(product);
  if (ends === "SW") return FITTING_SIZES.SW;
  if (ends === "NPT") return FITTING_SIZES.THRD;
  return /^(S\.S\.|D\.S\.)/.test(product.trim())
    ? FITTING_SIZES.BW_SS_DS
    : FITTING_SIZES.BW_CS_AS;
}

export function getFittingDimStandard(product: string): string {
  return getFittingEnds(product) === "BW" ? "ASME B16.9" : "ASME B16.11";
}

// Best-effort Pipe/Fitting/Flange classification from a product name — for
// rows that arrive without a stored category (tender items, PO edit loads).
export function inferItemCategory(product: string): "Pipe" | "Fitting" | "Flange" {
  const p = (product || "").toUpperCase();
  if (p.includes("FLANGE")) return "Flange";
  if (/(ELBOW|TEE\b|END CAP|COUPLING|STUB\s?END|CROSS\b|BOSS\b|PLUG|NIPPLE|REDUCER|UNION|BEND)/.test(p))
    return "Fitting";
  return "Pipe";
}
