-- AddValue: FAILED_INSPECTION to AlertType enum
ALTER TABLE `Alert` MODIFY COLUMN `type` ENUM('INSPECTION_DUE','LAB_TESTING_PENDING','DELIVERY_DEADLINE','MATERIAL_PREPARATION','STOCK_ALLOTMENT','PROCUREMENT_REQUIRED','FAILED_INSPECTION') NOT NULL;
