"use client";

import { useState, useEffect, use } from "react";
import { useRouter } from "next/navigation";
import { PageHeader } from "@/components/shared/page-header";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ArrowLeft } from "lucide-react";
import { format } from "date-fns";
import { toast } from "sonner";

export default function LabLetterDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const router = useRouter();
  const [letter, setLetter] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchLabLetter();
  }, [id]);

  const fetchLabLetter = async () => {
    try {
      const response = await fetch(`/api/quality/lab-letters/${id}`);
      if (response.ok) {
        const data = await response.json();
        setLetter(data.labLetter);
      } else {
        toast.error("Failed to load lab letter");
        router.push("/quality");
      }
    } catch (error) {
      toast.error("Failed to load lab letter");
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return (
      <div className="space-y-6">
        <div className="h-10 w-48 bg-muted animate-pulse rounded" />
        <div className="space-y-3">
          {[...Array(2)].map((_, i) => (
            <div key={i} className="h-24 bg-muted animate-pulse rounded" />
          ))}
        </div>
      </div>
    );
  }

  if (!letter) return null;

  const testIds = Array.isArray(letter.testIds)
    ? letter.testIds
    : [];

  return (
    <div className="space-y-6">
      <PageHeader
        title={letter.letterNo}
        description="Lab Test Letter Details"
      >
        <Button variant="outline" onClick={() => router.push("/quality")}>
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back
        </Button>
      </PageHeader>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Letter Details</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
            <div>
              <p className="text-sm text-muted-foreground">Letter Date</p>
              <p className="font-medium">
                {format(new Date(letter.letterDate), "dd MMM yyyy")}
              </p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Heat No</p>
              <p className="font-medium font-mono">
                {letter.heatNo || "—"}
              </p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Specification</p>
              <p className="font-medium">{letter.specification || "—"}</p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Size</p>
              <p className="font-medium font-mono">
                {letter.sizeLabel || "—"}
              </p>
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Generated By</p>
              <p className="font-medium">
                {letter.generatedBy?.name || "—"}
              </p>
            </div>
          </div>

          {testIds.length > 0 && (
            <div className="mt-4">
              <p className="text-sm text-muted-foreground mb-2">Test IDs</p>
              <div className="flex flex-wrap gap-2">
                {testIds.map((testId: string, i: number) => (
                  <Badge key={i} variant="outline">
                    {testId}
                  </Badge>
                ))}
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
