// Regenerates src/lib/fitting-flange-sizes.ts from the "new master" Excel files.
// Run: npx tsx scripts/gen-size-constants.ts
import fs from "node:fs";
import path from "node:path";
import { parseSectioned } from "../src/lib/masters/spec-import";

const dir = path.join(__dirname, "..", "new master");
const isSS = (p: string) => /^(S\.S\.|D\.S\.)/.test(p);

function pools(file: ReturnType<typeof parseSectioned>) {
  const cs = new Set<string>();
  const ss = new Set<string>();
  for (const sec of file.sections) {
    const target = isSS(sec.products[0] || "") ? ss : cs;
    for (const z of sec.sizes) target.add(z.label);
  }
  return { cs: [...cs], ss: [...ss] };
}

const bw = pools(parseSectioned(path.join(dir, "PRODUCT SPEC MASTER - BW FITTING.xlsx")));
const sw = pools(parseSectioned(path.join(dir, "PRODUCT SPEC MASTER - SW FITTING.xlsx")));
const thrd = pools(parseSectioned(path.join(dir, "PRODUCT SPEC MASTER - THRD FITTING.xlsx")));
const flange = parseSectioned(path.join(dir, "PRODUCT SPEC MASTER - FLANGE (1).xlsx"));

// SW/THRD size lists are identical across material classes — collapse.
const j = (a: string[]) => JSON.stringify(a, null, 2);
const flangeSizes = (() => {
  const seen = new Set<string>();
  const out: { label: string; dim: string }[] = [];
  for (const z of flange.sections.flatMap((s) => s.sizes)) {
    const k = `${z.label}§${z.dim}`;
    if (seen.has(k)) continue;
    seen.add(k);
    out.push(z);
  }
  return out;
})();

const out = `// GENERATED by scripts/gen-size-constants.ts from the "new master" Excel
// files — do not hand-edit the data blocks; re-run the script instead.
// Helpers at the bottom are hand-written.

export const FITTING_SIZES = {
  BW_CS_AS: ${j(bw.cs)},
  BW_SS_DS: ${j(bw.ss)},
  SW: ${j([...new Set([...sw.cs, ...sw.ss])])},
  THRD: ${j([...new Set([...thrd.cs, ...thrd.ss])])},
};

export const FLANGE_SIZES: { label: string; dim: string }[] = ${JSON.stringify(flangeSizes, null, 2)};

// ── helpers (hand-written) ──────────────────────────────────────────────────

// End connection from the product-name suffix convention:
// ", SW" → socket weld, ", SCRD" → threaded (NPT), otherwise butt-weld (SMLS).
export function getFittingEnds(product: string): "BW" | "SW" | "NPT" {
  if (/,\\s*SW$/i.test(product)) return "SW";
  if (/,\\s*SCRD$/i.test(product)) return "NPT";
  return "BW";
}

export function getFittingSizeOptions(product: string): string[] {
  const ends = getFittingEnds(product);
  if (ends === "SW") return FITTING_SIZES.SW;
  if (ends === "NPT") return FITTING_SIZES.THRD;
  return /^(S\\.S\\.|D\\.S\\.)/.test(product.trim())
    ? FITTING_SIZES.BW_SS_DS
    : FITTING_SIZES.BW_CS_AS;
}

export function getFittingDimStandard(product: string): string {
  return getFittingEnds(product) === "BW" ? "ASME B16.9" : "ASME B16.11";
}
`;

const dest = path.join(__dirname, "..", "src", "lib", "fitting-flange-sizes.ts");
fs.writeFileSync(dest, out);
console.log(
  `Wrote ${dest}\n  BW_CS_AS=${bw.cs.length} BW_SS_DS=${bw.ss.length} SW=${new Set([...sw.cs, ...sw.ss]).size} THRD=${new Set([...thrd.cs, ...thrd.ss]).size} FLANGE=${flangeSizes.length}`
);
